---
- name: Start and Enable a Service
  hosts: webservers
  become: yes

  vars:
    web_package: apache2
    service_name: apache2

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install the web package
      apt:
        name: "{{ web_package }}"
        state: present

    - name: Start and enable the service
      service:
        name: "{{ service_name }}"
        state: started
        enabled: yes