---
- name: Install Apache on Ubuntu and Amazon Linux
  hosts: webservers
  become: true
  tasks:
    - name: Install Apache on Ubuntu (apache2)
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Apache on Amazon Linux (httpd)
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Start and enable Apache on Ubuntu
      service:
        name: apache2
        state: started
        enabled: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Start and enable Apache on Amazon Linux
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_facts['os_family'] == "RedHat"
